### PR TITLE
[common-utils] Fix permission of scripts in containers

### LINKED ISSUE #387: The devcontainer-info script in common-utils 2 cannot be run by non-root users
It looks like the script's permissions are being updated by the Dev Container CLI?
devcontainers/cli#263

### PR DESCRIPTION
**Pull request by eitsupi**
Fix #387

The Dev Container CLI changes permission when copying scripts into the container and read permissions are removed for the non-root users.
Read permission must be added after copying the scripts into the container.

### CODE REVIEW

File: test/common-utils/devcontainer-info/Dockerfile [hunk 1]
```diff
@@ -0,0 +1,3 @@
+FROM mcr.microsoft.com/devcontainers/base:debian
```
Comment (samruddhikhandale) [inline test/common-utils/devcontainer-info/Dockerfile:1]:
```suggestion
FROM ubuntu:focal
```

The latest MCR image is built with `common-utils:1`, hence the `devcontainer-info` command is correctly configured. The newly added tests in this PR still pass against it without the `chmod +rx` changes.

Can we change the image here to avoid the false positives? thanks!

File: test/common-utils/devcontainer-info.sh [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+
+# Optional: Import test library
+source dev-container-features-test-lib
+
+check_info() {
+    local info=$1
+    check "devcontainer-info ${info}" sh -c "devcontainer-info | grep test-${info}"
+}
+
+# Definition specific tests
```
Comment (samruddhikhandale) [inline test/common-utils/devcontainer-info.sh:13]: Can we add a check to validate the non user?

> check "user" bash -c "whoami | grep vscode"

File: test/common-utils/scenarios.json [hunk 3]
```diff
@@ -114,5 +114,13 @@
                 "configureZshAsDefaultShell": true
             }
         }
+    },
+    "devcontainer-info": {
+        "build": {
+            "dockerfile": "Dockerfile"
+        },
+        "features": {
```
Comment (samruddhikhandale) [inline test/common-utils/scenarios.json:122]:
```suggestion
        "features": {
            "common-utils": {
                "username": "vscode",
                "userUid": "1000",
                "userGid": "1000",
                "upgradePackages": true,
                "installZsh": true
            }
        },
        "remoteUser": "vscode"
```

File: test/common-utils/devcontainer-info/Dockerfile (hunk 1 above)
Comment (samruddhikhandale) [reply test/common-utils/devcontainer-info/Dockerfile:1]: Have a PR out to make that version bump switch for the images. But I'll be waiting to merge that until this PR gets merged.

https://github.com/devcontainers/images/pull/307/files#r1065017365

**Review by samruddhikhandale — CHANGES_REQUESTED** [review]
Thanks for the fix, appreciate it! ✨ 

Left some minor comments.

**Comment by eitsupi** [comment]
Thanks for your review.
Fixed these and CI on my fork passed!
https://github.com/eitsupi/devcontainers-devcontainer-features/actions/runs/3878411868/jobs/6614551708

**Review by samruddhikhandale — APPROVED** [review]
🚀

**Comment by eitsupi** [comment]
Could you merge this?
