### PR TITLE
Fix regression with Azure CLI, privs

### LINKED ISSUE #270: error: `No module named 'runpy'`
It looks like certain python libraries are no longer being picked up correctly after the change in #258.

I get the following error running `az login`:

```bash
vscode ➜ /workspaces/devcontainer-az-login $ az login
Could not import runpy module
ModuleNotFoundError: No module named 'runpy'
```

I confirm that reverting to `ghcr.io/devcontainers/features/python:1.0.10` fixes the issue.

Additional debugging commands:

```bash
vscode ➜ /workspaces/devcontainer-az-login $ export
declare -x BROWSER="/vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/bin/helpers/browser.sh"
declare -x COLORTERM="truecolor"
declare -x DOCKER_BUILDKIT="1"
declare -x GIT_ASKPASS="/vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/extensions/git/dist/askpass.sh"
declare -x GIT_EDITOR="code --wait"
declare -x HOME="/home/vscode"
declare -x HOSTNAME="5cf89a0f98a6"
declare -x LANG="en_US.UTF-8"
declare -x LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
declare -x NVM_BIN="/usr/local/share/nvm/versions/node/v16.18.1/bin"
declare -x NVM_CD_FLAGS=""
declare -x NVM_DIR="/usr/local/share/nvm"
declare -x NVM_INC="/usr/local/share/nvm/versions/node/v16.18.1/include/node"
declare -x NVM_SYMLINK_CURRENT="true"
declare -x OLDPWD
declare -x PATH="/vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/bin/remote-cli:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/share/nvm/versions/node/v16.18.1/bin:/usr/local/python/current/bin:/usr/local/py-utils/bin:/usr/local/share/nvm/versions/node/v16.18.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/vscode/.local/bin"
declare -x PIPX_BIN_DIR="/usr/local/py-utils/bin"
declare -x PIPX_HOME="/usr/local/py-utils"
declare -x PROMPT_DIRTRIM="4"
declare -x PWD="/workspaces/devcontainer-az-login"
declare -x PYTHON_PATH="/usr/local/python/current"
declare -x REMOTE_CONTAINERS="true"
declare -x REMOTE_CONTAINERS_IPC="/tmp/vscode-remote-containers-ipc-e4c7657c19de2ca1e38963832cd3400ae6b88306.sock"
declare -x REMOTE_CONTAINERS_SOCKETS="[\"/tmp/vscode-ssh-auth-e4c7657c19de2ca1e38963832cd3400ae6b88306.sock\",\"/home/vscode/.gnupg/S.gpg-agent\"]"
declare -x SHELL="/bin/bash"
declare -x SHLVL="2"
declare -x SSH_AUTH_SOCK="/tmp/vscode-ssh-auth-e4c7657c19de2ca1e38963832cd3400ae6b88306.sock"
declare -x TERM="xterm-256color"
declare -x TERM_PROGRAM="vscode"
declare -x TERM_PROGRAM_VERSION="1.73.0"
declare -x USER="vscode"
declare -x VSCODE_GIT_ASKPASS_EXTRA_ARGS=""
declare -x VSCODE_GIT_ASKPASS_MAIN="/vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/extensions/git/dist/askpass-main.js"
declare -x VSCODE_GIT_ASKPASS_NODE="/vscode/vscode-server/bin/linux-x64/8fa188b2b301d36553cbc9ce1b0a146ccb93351f/node"
declare -x VSCODE_GIT_IPC_HANDLE="/tmp/vscode-git-4b512c3a7f.sock"
declare -x VSCODE_IPC_HOOK_CLI="/tmp/vscode-ipc-207d9707-6442-437c-a01b-5a6ccc775283.sock"
vscode ➜ /workspaces/devcontainer-az-login $ which az
/usr/local/python/current/bin/az
vscode ➜ /workspaces/devcontainer-az-login $ which python
/usr/local/python/current/bin/python
vscode ➜ /workspaces/devcontainer-az-login $ python -c "import runpy; print(runpy.__file__)"
/usr/lib/python3.9/runpy.py
```

Originally from [1121](https://github.com/Azure/azure-dev/issues/1121)

### PR DESCRIPTION
**Pull request by Chuxel**
Due to https://github.com/Azure/azure-cli/issues/23376, the Azure CLI fails to start if the `os-provided` version of python is installed. This points to a broader challenge with the strategy of mapping `/usr` to a symlink which also results in group priv changes.

This PR updates the model by only symlinking specific binaries that are referenced in PATH config rather than everything.

Resolves #270

### CODE REVIEW

File: src/python/install.sh [hunk 1]
```diff
@@ -344,13 +344,20 @@ install_python() {
...
-        mkdir -p "${PYTHON_INSTALL_PATH}"
-        add_symlink
+        local current_bin_path="${CURRENT_PATH}/bin"
+        if [ "${OVERRIDE_DEFAULT_VERSION}" = "true" ]; then
+            rm -rf "${current_bin_path}"
+        fi
+        if [ ! -d "${current_bin_path}" ] ; then
+            mkdir -p "${current_bin_path}"
+            # Add an interpreter symlink but point it to "/usr" since python is at /usr/bin/python, add other alises
+            ln -s "${INSTALL_PATH}/bin/python3" "${current_bin_path}/python3"
```
Comment (samruddhikhandale) [inline src/python/install.sh:354]: I believe you are hoping the `/usr/local/python/current` folder to be owned by `USERNAME:python` ?

image

Then the condition needs to be changed 🤔 

https://github.com/devcontainers/features/blob/e9c8ba5cf598a65957d8f25cd9515e0db88e4da0/src/python/install.sh#L407

Comment (Chuxel) [reply src/python/install.sh:354]: Given this is the OS installed version of python, we shouldn't be messing around with privs TBH.  It was actually like that before.

Comment (Chuxel) [reply src/python/install.sh:354]: Updated

File: src/python/install.sh [hunk 2]
```diff
@@ -344,13 +344,20 @@ install_python() {
...
 
-        ln -s "${INSTALL_PATH}/bin/python3" "${INSTALL_PATH}/bin/python"
-        ln -s "${INSTALL_PATH}/bin/pydoc3" "${INSTALL_PATH}/bin/pydoc"
-        ln -s "${INSTALL_PATH}/bin/python3-config" "${INSTALL_PATH}/bin/python-config"
-
-        # Add the current symlink but point it to "/usr" since python is at /usr/bin/python
-        mkdir -p "${PYTHON_INSTALL_PATH}"
-        add_symlink
+        local current_bin_path="${CURRENT_PATH}/bin"
+        if [ "${OVERRIDE_DEFAULT_VERSION}" = "true" ]; then
```
Comment (samruddhikhandale) [inline src/python/install.sh:348]: `OVERRIDE_DEFAULT_VERSION` is useful for installing additional versions of python. 

Thanks for syncing it. However, looks like there is an existing bug for that.

Could we change this 👇  https://github.com/devcontainers/features/blob/74f75a51f25dfcb3734f6c43a8bee9a45867f024/src/python/install.sh#L343 

to 👇 

```
if [ ${version} = "os-provided" ] || [ ${version} = "system" ]; then 
```

Comment (Chuxel) [reply src/python/install.sh:348]: We wouldn't want to add all those versions to the path tho right?  As it is, the PYTHON_INSTALL_PATH is always updated, but the PATH is only updated if you aren't using a system version (which would already be in the PATH).  The $version is in a sub-folder from what I was reading.

Comment (Chuxel) [reply src/python/install.sh:348]: Oh wait - that link poiinted to the wrong spot.  Got it. Yeah, that was an existing bug.

Comment (samruddhikhandale) [reply src/python/install.sh:348]: Great! thanks

Comment (Chuxel) [reply src/python/install.sh:348]: Fixed!

**Review by samruddhikhandale — APPROVED** [review]
looks good to me! Thanks
